### PR TITLE
[TASK] Add docker registry container

### PR DESCRIPTION
**Pull request by lukaszuznanski**
WIP

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
@oliverklee  https://gitlab.typo3.org/qa/example-extension/-/pipelines/9653

**Comment by oliverklee** [comment]
@lukaszuznanski Is this still WIP? And could you please rebase to resolve the conflicts?

**Comment by lukaszuznanski** [comment]
@oliverklee if we merge gitlab CI tests, then I will include tests in this PR and we can merge complete gitlab ci file :)

**Comment by oliverklee** [comment]
@lukaszuznanski  I've just merged #103.

**Comment by lukaszuznanski** [comment]
https://gitlab.typo3.org/qa/example-extension/-/pipelines/9672

**Pull request closed without merging**
