### PR TITLE
Create a service and test it

### LINKED ISSUE #525: Demonstrate Services and Utility classes
Controllers in Extbase should be lean by definition. Business logic should therefore be placed in the namespace VENDOR/Extension/Services if they are stateful and VENDOR/Extension/Utility if they are stateless.

Having business logic beyond control flow in a Controller is a common mistake made by beginners. Business logic in controllers causes problems later on. 

So I would love to see an example of Services and Utility classes.

### PR DESCRIPTION
**Pull request by linawolf**
resolves #525

### CODE REVIEW

**Comment by linawolf** [comment]
As this feature is planed for 2.1.0 it can be reviewed now

**Comment by oliverklee** [comment]
We (the QA best practices team and @linawolf) should meet and talk about which features are needed for the book and how they could make sense for the Tea extension first.

**Comment by linawolf** [comment]
So isn't tickets and pull requests a valid tool of communication?

**Comment by oliverklee** [comment]
No, for discussing which features make sense, I'd prefer actual talking (as this is way faster). Particularly, I'd like to avoid people writing code for changes that will not make it into the code base at all.

**Comment by oliverklee** [comment]
And as new features need a team decision and we come to our decisions during the team calls, a PR or a ticket will not work for making decisions.

**Comment by linawolf** [comment]
Well, you yourself scheduled my ticket  for a release. I made a ticket up front explaining my feature request. I do not have time on Wednesdays and my prefered way of communication are tickets as you can always read lateron why this or that communication was made. 

Use this or leave it.

**Pull request closed without merging**
