### PR TITLE
[FEATURE] Allow to hide teas based on fe_groups

### LINKED ISSUE #555: Allow making records  visible only for certain fe_groups
With 
$GLOBALS['TCA'][$table]['ctrl']['enablecolumns']['fe_group']

https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Ctrl/Properties/Enablecolumns.html

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Resolves #555

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
Tested with v11.5 and v12.

V12 allows you to add array keys, but that wouldn't work in v11, so I didn't add them.

**Comment by brotkrueml** [comment]
> Tested with v11.5 and v12.
> 
> V12 allows you to add array keys, but that wouldn't work in v11, so I didn't add them.
> 
> That's what is reported within the tests. Should I add a condition to provide different config based on version?
> 
> `The TCA field 'fe_group' of table 'tx_tea_domain_model_product_tea' uses the legacy way of defining 'items'. Please switch to associated array keys: label, value, icon, group, description.`

You can add both: 0, 1, label, value. Then the deprecation should be avoided.

**Comment by DanielSiepmann** [comment]
> You can add both: 0, 1, label, value. Then the deprecation should be avoided.

Thanks @brotkrueml for your suggestion, but it doesn't help.

**Comment by brotkrueml** [comment]
> > You can add both: 0, 1, label, value. Then the deprecation should be avoided.
> 
> Thanks @brotkrueml for your suggestion, but it doesn't help.

Sorry, then you might need something like this to avoid the deprecation:

https://github.com/brotkrueml/typo3-matomo-widgets/blob/main/Configuration/SiteConfiguration/Overrides/sites.php#L79-L86

I use label/value by default and then change to 0/1 when v11.

**Comment by DanielSiepmann** [comment]
The phpunit issue with 12.3 seems unrelated to my change. I don't know what's causing them.

**Comment by oliverklee** [comment]
The PHPUnit failure is in deed unrelated, and we need to solve it first. The cause is that in V12 `ActionController` does not have the `forward` or `redirect` methods anymore, and hence we cannot mock them anymore. We'll need to add a version switch for this.

**Comment by DanielSiepmann** [comment]
I can do that @oliverklee, give me some minutes. Still wondering why I don't have the issue locally. But never mind.

**Comment by oliverklee** [comment]
There was a very recent change in the TYPO3 TF switching to `onlyMethods` that made this problem visible. With a composer update, possibly the problem will occur locally as well.

**Comment by DanielSiepmann** [comment]
Looks like composer install without `composer.lock` etc. still doesn't fetch new commits into composer cache. At least that would explain why removing all files and running `composer install` didn't reveal the issue. I now ran `composer update` and could reproduce, fix: https://github.com/TYPO3-Documentation/tea/pull/799.

**Review by oliverklee — APPROVED** [review]

**Pull request merged**
