### PR TITLE
[TASK] Split GitLab jobs

### PR DESCRIPTION
**Pull request by lukaszuznanski**
https://gitlab.typo3.org/qa/example-extension/-/pipelines/15250

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
https://gitlab.typo3.org/qa/example-extension/-/pipelines/15250

**Review by oliverklee — COMMENTED** [review]
Concerning the file structure: I don't understand why the directory is called `templates`. Are those files intended to be copied and changed instead of being used directly?

**Comment by lukaszuznanski** [comment]
> Concerning the file structure: I don't understand why the directory is called `templates`. Are those files intended to be copied and changed instead of being used directly?

Those files should be used directly. I changed directory name.

**Review by oliverklee — APPROVED** [review]
LGTM.

**Pull request merged**
